Seminar1 필수과제
GO-SOPT-ANDROID/hyeseon-baek pull request #2
Opened 2023-04-05 18:46 UTC by sxunea

### Seminar1 - UI Basic

### 구현 화면
---
- 로그인
- 회원가입
- 자기소개

### 상세 기술
---
- registerActivityForResult, putExtra
- inputType
- Toast, SnackBar
- intent

2023-04-07 12:00 UTC, b1urrrr approved these changes
첫 주차부터 과제하시느라 고생하셨습니다! PR에 실행화면 첨부해주시면 감사하겠습니다 🙃
불필요한 줄바꿈들은 제거해주시고 code reformat 단축키(Window 기준 Ctrl + Alt + L) 자주 눌러주시면 더 좋을 것 같슴다
코드 수정해주시고 reviewers에서 re-request 해주시면 달려올게요 💨

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="fullSensor"
크 activity 속성 설정 꼼꼼하게 하셨네요 👏👏
앱잼에서는 `screenOrientation="portrait"`으로 하시는 것이... 정신건강에 좋을 것입니다 🫠

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/MainActivity.kt
> +            binding.mainTvSpecial.text = "SharedPreference에 특기저장X"
코틀린 파일에서도 string 소스를 추출하여 하드 코딩을 줄이는 것을 추천 드립니다 ㅎㅎ
Window 기준 Alt + Enter를 통해 편하게 "Extract string resource"가 가능합니다!

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/join/JoinActivity.kt
> +    }
```suggestion
        setContentView(binding.root)
        setJoinbtnEvent()
    }
```
불필요한 줄바꿈은 없애봅시다!

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/join/JoinActivity.kt
> +                setResult(RESULT_OK, intent)
```suggestion
                Intent(this@JoinActivity, LoginActivity::class.java).apply {
                    putExtra("USER", userData)
                    setResult(RESULT_OK, this)
                }
```
스코프 함수 `apply`나 `also`를 활용하여 보다 코틀린스럽게 코드를 작성할 수 있습니다 ㅎㅎ

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/join/JoinActivity.kt
> +            }
```suggestion
                makeSnackBar(getString(R.string.join_success_string))
                return
            }
            makeSnackBar(getString(R.string.join_fail_string))
```

사람마다 지향하는 코드 스타일이 다르겠지만 early return 패턴으로 작성해볼 수도 있습니다!

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +        }
요 로직도 함수화를 해주면 좋을 것 같슴다

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +                Toast.makeText(this@LoginActivity, getString(R.string.login_success_string), Toast.LENGTH_SHORT).show()
토스트도 `makeSnackbar`처럼 함수화를 해줄 수 있을 것 같습니다!
스낵바나 토스트를 발생시키는 함수는 프로젝트 전역에서 재사용될 수 있기 때문에 Activity나 Context, View의 확장함수를 사용하는 방법을 찾아보셔도 좋을 것 같습니다 :)

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +                    userData = result.data?.getParcelableExtra("USER",User::class.java)
아래와 같이 Extra Data의 이름(key값)을 상수화해주면 다른 클래스에서도 재사용이 가능하며, 하드 코딩을 줄일 수 있습니다!
```
companion object {
        const val EXTRA_USER = "USER"
}
```

그런데 Intent 클래스 내부에 `EXTRA_USER`라는 상수가 이미 정의되어 있어서 저는 그냥 이걸 사용했습니다 ㅎㅎ

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/utiil/utilFun.kt
> +}
object에 SharedPreferences에 대한 함수를 선언하여 재사용할 수 있도록 구현하신 점 너무 좋습니다 👍👍
[Android KTX](https://developer.android.com/kotlin/ktx)를 활용하여 좀 더 코드를 줄일 수도 있습니다!
[Google Developers 블로그 글 SharedPreferences 편집 부분](https://developers-kr.googleblog.com/2018/02/introducing-android-ktx-even-sweeter-kotlin-development-for-android.html)을 참고해주세요 :)

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/res/layout/activity_join.xml
> +        android:id="@+id/join_tv_ID"
xml의 id값은 lower_snake_case로 네이밍하는 것이 관례이므로 대문자 대신 소문자를 사용해주세요!
```suggestion
        android:id="@+id/join_tv_id"
```

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintVertical_bias="0.132" />
의도하신 게 아니라면 `layout_constraitnVertical_bias` 속성은 지워주세요!

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintDimensionRatio="1:1"
`layout_constraintDimensionRatio`속성이 적용되려면 `layout_width` 속성을 0dp로 설정해주셔야할 것 같습니다!

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/res/layout/activity_main.xml
> +        android:text="이름 : "
귀찮긴 하지만 xml에서도 텍스트 추출을 통해 보일러플레이트를 줄여봅시다 ㅎㅎ

2023-04-07 12:00 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/MainActivity.kt
> +        binding.mainTvSpecial.text = getString(R.string.main_tv_special) + userData?.special
```suggestion
        binding.mainTvName.append(userData?.name)
        binding.mainTvSpecial.append(userData?.special)
```
`append` 함수를 활용하면 좀 더 간결하게 표현할 수 있습니다!

2023-04-07 12:02 UTC, b1urrrr requested changes
뭐야 실수로 approve로 제출했네요 🤦‍♀️

2023-04-08 00:57 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/data/User.kt
> +):Parcelable
오.. Parcelable
따라친거일까요 아님 원리를 알고 적용하신것일까요 ㅎㅎ

2023-04-08 00:57 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/presentation/MainActivity.kt
> +    private var userData : User? = null
null 로 채워준 이유가 있을까요

2023-04-08 00:57 UTC, daehwan2da commented on app/src/main/java/org/android/go/sopt/presentation/join/JoinActivity.kt
> +                val userData = User(
[namedArgument](https://kotlinlang.org/docs/functions.html#named-arguments) 적극적으로 활용해봅시다

현재 생성자가 (String, String, String, String) 이여서 name이랑 password 를 실수로 거꾸로 넣어버리면 어케될까요
User(binding.joinEtPW.text.toString(), binding.joinEtID.text.toString(), ...) 
정상동작은 하겠지만, id 에 password 가 담기는 문제가 발생할 수 있겠네요..

java 에서 생성자를 쓰면서 발생가능한 취약점이 이런 부분인데요, kotlin 에서는 named-argument 로 이런 문제를 해결하고자 했답니다~

2023-04-08 19:28 UTC, lsakee commented on app/src/main/res/layout/activity_join.xml
> +        android:textStyle="bold"
style로 지정하면 재사용이 용이할 거 같습니다 ㅎㅎ

2023-04-08 19:28 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +                Toast.makeText(this@LoginActivity, getString(R.string.login_success_string), Toast.LENGTH_SHORT).show()
토스트도 함수화 시키면 재사용이 용이 할 거 같습니다.

2023-04-08 19:28 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/presentation/join/JoinViewModel.kt
> +        return !id.isNullOrBlank() && id.length in 6..10 && !pw.isNullOrBlank() && pw.length in 8..12
상수로 설정해주셔도 될거 같아요! 입력 길이

2023-04-08 19:28 UTC, lsakee commented on app/src/main/res/layout/activity_main.xml
> +        android:text="이름 : "
이름 값 텍스트 정의하시면 좋을거 같습니다.

2023-04-10 15:59 UTC, sxunea commented on app/src/main/java/org/android/go/sopt/data/User.kt
> +):Parcelable
제가 아는 바로는 Bundle을 사용할때 일반 데이터 클래스를 담는 경우 map이 아니어서 사용합니다 ! 그래서 보통 데이터 클래스를 만들때 parcelize 해놓는 편인데 보충해주실 다른 원리나 이유가 있나요 ㅎㅎㅎ

2023-04-10 17:00 UTC, b1urrrr approved these changes
LGTM 👍

2023-04-11 10:27 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/util/UtilObject.kt
> +object UtilObject {
SharedPreferences 관련 로직만 포함되어 있으니까 이름을 PrefUtilObject 이런식으로 해도 좋을 거 같아요!

2023-04-11 10:27 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/presentation/join/JoinActivity.kt
> +            isCheck()
함수 이름만 봐도 어떤 역할을 하는지 알 수 있도록 조금 더 길게 함수명을 작성해도 좋을 거 같아요! 그리고 이렇게 하다보면 자연스럽게 한 함수에서는 최대한 하나의 역할만 하도록 기능을 분리시키게 돼서 좋더라구요!

2023-04-11 10:27 UTC, leeeha commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +    }
키보드 숨기는 함수도 확장 함수로 만들어서 여러 곳에서 쓸 수 있게 만들 수 있더라구요! (저도 채연이 코드 보고 알았어요 ㅎㅎ)

2023-04-14 16:47 UTC, b1urrrr approved these changes
리포지토리 Access 설정에서 팀 권한 Write로 바꾸시면 머지 가능해질 거예요!

2023-04-14 16:51 UTC, merged