Feature/seminar4
GO-SOPT-ANDROID/hyeseon-baek pull request #6
Opened 2023-05-12 02:18 UTC by sxunea

2023-05-12 05:39 UTC, lsakee reviewed
Hilt까지 너무 잘하시네요! 제가 좋아하는 코드 스타일이시네요

2023-05-12 05:39 UTC, lsakee commented on app/build.gradle
> +}
version 관리 좋네요!

2023-05-12 05:39 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/data/service/FollowerApiService.kt
> +    @GET("api/users?page=2")
string 빼시면 더  좋아보이네요!

2023-05-12 05:39 UTC, lsakee commented on app/src/main/java/org/android/go/sopt/di/ApiModule.kt
> +    annotation class ReqresRetrofit
반환 type 이 같아서 식별자를 넣어 주셨군요!

2023-05-14 05:46 UTC, Dan2dani reviewed
잠깐 왔다갑니당 >^< 혜선 언니 너무 잘하네용 ~

2023-05-14 05:46 UTC, Dan2dani commented on app/src/main/java/org/android/go/sopt/data/model/response/ResponseFollowerDto.kt
> +    fun convertToFollower(): List<Follower> {
좋네용!

2023-05-14 05:46 UTC, Dan2dani commented on app/src/main/java/org/android/go/sopt/presentation/main/home/HomeAdapter.kt
> +                return newItem.email == oldItem.email
좋습니다

2023-05-14 05:46 UTC, Dan2dani commented on app/src/main/java/org/android/go/sopt/presentation/main/home/HomeFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
잘하시네용 ~~~ 함수화도 너무 좋습니다

2023-05-14 05:46 UTC, Dan2dani commented on app/src/main/java/org/android/go/sopt/data/model/response/ResponseFollowerDto.kt
> +        val first_name: String,
보통 변수는 camelCase로 작석하는게 일반적인데요! 바꿔줍시당~

2023-05-15 05:01 UTC, b1urrrr requested changes
크 도메인 레이어 분리하고 힐트까지 적용하셨네요!
한번 데이터 소스도 공부해보시면 좋을 것 같습니당
이번 주도 과제 하시느라 고생하셨습니다 👍👍

2023-05-15 05:01 UTC, b1urrrr commented on app/build.gradle
> +    implementation "androidx.fragment:fragment-ktx:1.5.4"
[팟장님 과제에 의진님께서 남겨주신 리뷰](https://github.com/GO-SOPT-ANDROID/junseo-kim/pull/1#discussion_r1178782978)를 그대로 가져왔습니다 ㅎㅎ

![image](https://user-images.githubusercontent.com/70993562/236547491-543201b6-966e-40fe-baf5-f9e0b8fe572c.png)

[종속성 트리](https://stackoverflow.com/questions/62789101/why-some-projects-import-androidx-activity-ktx-or-not)에 포함되어 있어서 아래 dependency 만 사용하셔도 된다고 합니다!
```
 implementation 'androidx.fragment:fragment-ktx:1.5.7
```

2023-05-15 05:01 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/data/model/response/ResponseFollowerDto.kt
> +    }
```suggestion
    fun convertToFollower() = data.map {
            Follower(
                avatar = it.avatar,
                email = it.email,
                firstName = it.first_name
            )
        }
    }
```
Single Expression 함수로 정의하면 더 깔끔할 것 같습니당

2023-05-15 05:01 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/data/model/response/ResponseSignInDto.kt
> +    val data: SignInData,
보통 서버 파트와 협업을 하게 되면 `data`의 타입만 변동되고 `status`나 `message` 파라미터는 고정되어 반복적으로 사용하게 되는 경우가 많습니다. 이럴 때 제너릭을 활용한 Wrapper Class를 만들면 보일러 플레이트를 줄일 수 있을 것입니다!

2023-05-15 05:01 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/data/service/FollowerApiService.kt
> +    @GET("api/users?page=2")
`page`는 유동적으로 바뀔 수 있는 값에 해당하기 때문에 `@Query`를 활용해보시는 걸 추천 드립니다!

2023-05-15 05:01 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/di/RetrofitModule.kt
> +        .baseUrl(REQRES_BASE_URL)
```suggestion
    import org.android.go.sopt.BuildConfig.USER_BASE_URL
    import org.android.go.sopt.BuildConfig.REQRES_BASE_URL
    
    @Singleton
    @Provides
    @ApiModule.SignRetrofit
    fun provideSpringRetrofit(okHttpClient: OkHttpClient): Retrofit = Retrofit.Builder()
        .baseUrl(USER_BASE_URL)
        .client(okHttpClient)
        .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))
        .build()

    @Singleton
    @Provides
    @ApiModule.ReqresRetrofit
    fun provideReqresRetrofit(okHttpClient: OkHttpClient): Retrofit = Retrofit.Builder()
        .baseUrl(REQRES_BASE_URL)
```
상수를 import 해주면 변수를 따로 선언할 필요가 없어질 것 같습니다!

2023-05-15 05:01 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginViewModel.kt
> +class LoginViewModel @Inject constructor(private val apiAuthRepository: AuthRepository): ViewModel(){
```suggestion
import dagger.hilt.android.lifecycle.HiltViewModel

@HiltViewModel
class LoginViewModel @Inject constructor(
    private val apiAuthRepository: AuthRepository
) : ViewModel() {
```
import와 code reformat을 통해 코드 가독성을 개선해주면 좋을 것 같습니다!

2023-05-15 05:01 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignupActivity.kt
> +    }
`dispatchTouchEvent`를 통해 키보드가 숨겨지도록 구현하셨기 때문에 클릭 리스너는 제거하는 것이 좋을 것 같습니다!

2023-05-15 05:01 UTC, b1urrrr commented on app/build.gradle
> +    implementation("com.squareup.okhttp3:logging-interceptor")
implementation 할 때 Kotlin 스크립트(KTS)와 Groovy 문법이 섞여있는데 통일 시켜주시면 좋을 것 같습니다 :) [공식문서에 따르면 Groovy보다 KTS로 gradle을 작성하는 것이 선호된다고 합니다.](https://developer.android.com/build/migrate-to-kotlin-dsl)

2023-05-15 05:01 UTC, b1urrrr commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'
`annotationProcessor`은 자바의 어노테이션 프로세싱 툴에 해당합니다.
코틀린의 어노테이션 프로세싱 툴인 `kapt`를 사용하는 것이 좋을 것 같습니다!

2023-05-15 05:01 UTC, b1urrrr commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignupViewModel.kt
> +    }
여기 로직이 조금 이상한 것 같은데 혹시 회원가입 버튼 활성화 잘 되구 있나요?

2023-05-15 15:21 UTC, sxunea commented on app/src/main/java/org/android/go/sopt/data/model/response/ResponseFollowerDto.kt
> +        val first_name: String,
변경했습니다 감사합니당 ~ 👍

2023-05-15 15:22 UTC, sxunea commented on app/src/main/java/org/android/go/sopt/presentation/signup/SignupViewModel.kt
> +    }
자동로그인돼서 몰랐나봐요 ,, 바꿔놓았어요 고맙습니다 ㅠㅠㅠ 👍

2023-05-16 15:56 UTC, b1urrrr approved these changes
LGTM ❤️

2023-05-20 02:11 UTC, merged